name: Run (deliberately flaky) tests with retry

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/dotnet/sdk
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - run: pwsh ./run-tests.ps1
